// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/06/2026, 00:11:22
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/williambeto/Development/cup/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/plugins/**/*.{js,ts,mjs}","/home/williambeto/Development/cup/app/composables/**/*.{js,ts,mjs}","/home/williambeto/Development/cup/app/utils/**/*.{js,ts,mjs}","/home/williambeto/Development/cup/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/williambeto/Development/cup/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;